# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapreduce.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapreduce.proto\" \n\nMapRequest\x12\x12\n\ninput_data\x18\x01 \x01(\t\"\"\n\x0bMapResponse\x12\x13\n\x0bmapped_data\x18\x01 \x03(\t\"$\n\rReduceRequest\x12\x13\n\x0bmapped_data\x18\x01 \x03(\t\"&\n\x0eReduceResponse\x12\x14\n\x0creduced_data\x18\x01 \x01(\t2\\\n\tMapReduce\x12\"\n\x03Map\x12\x0b.MapRequest\x1a\x0c.MapResponse\"\x00\x12+\n\x06Reduce\x12\x0e.ReduceRequest\x1a\x0f.ReduceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapreduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPREQUEST']._serialized_start=19
  _globals['_MAPREQUEST']._serialized_end=51
  _globals['_MAPRESPONSE']._serialized_start=53
  _globals['_MAPRESPONSE']._serialized_end=87
  _globals['_REDUCEREQUEST']._serialized_start=89
  _globals['_REDUCEREQUEST']._serialized_end=125
  _globals['_REDUCERESPONSE']._serialized_start=127
  _globals['_REDUCERESPONSE']._serialized_end=165
  _globals['_MAPREDUCE']._serialized_start=167
  _globals['_MAPREDUCE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
